# Generated by Django 3.1 on 2020-08-18 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budgets',
            fields=[
                ('bID', models.IntegerField(primary_key=True, serialize=False)),
                ('bName', models.CharField(choices=[('Grocery', 'Grocery'), ('Fast Food', 'Fast Food'), ('Restaurants', 'Restaurants'), ('Bars', 'Bars'), ('Coffee', 'Coffee'), ('Dessert', 'Dessert')], default='Grocery', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('eID', models.IntegerField(primary_key=True, serialize=False)),
                ('eAmount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('eDate', models.DateField()),
                ('bID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget', to='budget.budgets')),
            ],
        ),
    ]
