# Generated by Django 3.1 on 2020-08-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budgets_bamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgets',
            name='bID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='eID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
