# Generated by Django 3.1 on 2020-08-20 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0003_auto_20200818_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgets',
            name='bUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='budget_owner', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenses',
            name='eUser',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='expense_owner', to='auth.user'),
            preserve_default=False,
        ),
    ]
